// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZwH0ZCBFR54gTdQeY8NdEJcI7u5G9wnc',
    appId: '1:290008813344:web:9aed83ccb21839cdce9145',
    messagingSenderId: '290008813344',
    projectId: 'face-recognation-f4bb1',
    authDomain: 'face-recognation-f4bb1.firebaseapp.com',
    storageBucket: 'face-recognation-f4bb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzSzkRXvyRh6sF-O3ASJp_y2mmE0xx5H8',
    appId: '1:290008813344:android:40a5833450e01490ce9145',
    messagingSenderId: '290008813344',
    projectId: 'face-recognation-f4bb1',
    storageBucket: 'face-recognation-f4bb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCatkG8Ja_bygzGiwCJabdU3SVC1P7LfF8',
    appId: '1:290008813344:ios:f7398d4f5f2442efce9145',
    messagingSenderId: '290008813344',
    projectId: 'face-recognation-f4bb1',
    storageBucket: 'face-recognation-f4bb1.firebasestorage.app',
    iosBundleId: 'com.vivasemmedo.vivaClienteV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCatkG8Ja_bygzGiwCJabdU3SVC1P7LfF8',
    appId: '1:290008813344:ios:f7398d4f5f2442efce9145',
    messagingSenderId: '290008813344',
    projectId: 'face-recognation-f4bb1',
    storageBucket: 'face-recognation-f4bb1.firebasestorage.app',
    iosBundleId: 'com.vivasemmedo.vivaClienteV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtIMm2jaokV8bJDheCfMhd0Gw5Yo0Zi0E',
    appId: '1:640068598484:web:2f4eb1af6b69488d5c5941',
    messagingSenderId: '640068598484',
    projectId: 'viva-sem-medo-v2-mz25',
    authDomain: 'viva-sem-medo-v2-mz25.firebaseapp.com',
    storageBucket: 'viva-sem-medo-v2-mz25.firebasestorage.app',
  );
}